config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  resources :kittens

  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def show
    @kitty = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @kitty }
    end
  end

  def new
    @kitty = Kitten.new
  end

  def create
    @kitty = Kitten.new(kitten_params)
    if @kitty.save
      redirect_to @kitty
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end

  def edit
    @kitty = Kitten.find(params[:id])
  end

  def update
    @kitty = Kitten.find(params[:id])
      if @kitty.update(kitten_params)
        flash[:success] = "Kitten was successfully updated"
        redirect_to @kitty
      else
        flash[:error] = "Something went wrong"
        render :edit
      end
  end

  def destroy
    @kitty = Kitten.find(params[:id])
    if @kitty.destroy
      flash[:success] = "Kitten was successfully deleted."
      redirect_to kittens_path
    else
      flash[:error] = "Something went wrong"
      redirect_to @kitty
    end
  end


  private

  def kitten_params
    params.require(:kitten).permit(
      :id,
      :name,
      :age,
      :cuteness,
      :softness
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.number_field :age, min: 0 %>

  <%= f.label :cuteness %>
  <%= f.number_field :cuteness, min: 0, max: 10 %>

  <%= f.label :softness %>
  <%= f.number_field :softness, min: 0, max: 10 %>

  <%= f.submit kitten.new_record? ? "Create" : "Update" %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Info for: <%= @kitty.name %></h1>

<%= link_to "Delete Kitten", @kitty, 
            data: { turbo_method: :delete, 
                    turbo_confirm: "Are you sure?" } %>
<%= link_to "Back to all kittens", kittens_path %>
<%= render 'form', kitten: @kitty %>

app/views/kittens/index.html.erb
<h1>All kittens</h1>
<%= link_to "Add a kitty", new_kitten_path%>
<% @kittens.each do |kitten| %>
    <h2><%= link_to "Name: #{kitten.name}", kitten %></h2>
<% end %>

app/views/kittens/new.html.erb
<h1>Create your Kitty</h1>

<%= render 'form', kitten: @kitty %>

app/views/kittens/show.html.erb
<h1>Kitty showcase</h1>

<%= link_to "Delete Kitten", @kitty, 
            data: { turbo_method: :delete, 
                    turbo_confirm: "Are you sure?" } %>
                    
<%= link_to "Back to all kittens", kittens_path %>

<h2>Name: <%= @kitty.name %></h2>
<h3>age: <%= @kitty.age %></h3>
<h3>Cuteness score: <%= @kitty.cuteness %></h3>
<h3>softness score: <%= @kitty.softness %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Kittens" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <div class="flash <%= type %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>